name: Deploy CSlant Server - Dispatch

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Remote Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_WEB_2 }}
          username: ${{ secrets.REMOTE_USERNAME_WEB_2 }}
          password: ${{ secrets.REMOTE_PASS_WEB_2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT_WEB_2 }}
          script: |
            ${{ github.event.client_payload.script_runner }}
