name: Deploy CSlant Server - W2

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      SCRIPT_RUNNER:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Debug Secrets
        run: |
          echo "REMOTE_HOST_WEB_2=${{ secrets.REMOTE_HOST_WEB_2 }}" | sed 's/./& /g'
          echo "REMOTE_USERNAME_WEB_2=${{ secrets.REMOTE_USERNAME_WEB_2 }}" | sed 's/./& /g'
          echo "REMOTE_PASS_WEB_2=${{ secrets.REMOTE_PASS_WEB_2 }}" | sed 's/./& /g'
          echo "REMOTE_PORT_WEB_2=${{ secrets.REMOTE_PORT_WEB_2 }}" | sed 's/./& /g'
          echo "SSH_PRIVATE_KEY_WEB_2=${{ secrets.SSH_PRIVATE_KEY_WEB_2 }}" | sed 's/./& /g'
