name: Deploy CSlant Server - W2 via Dispatch

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Deploy to Remote Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_WEB_2 }}
          username: ${{ secrets.REMOTE_USERNAME_WEB_2 }}
          password: ${{ secrets.REMOTE_PASS_WEB_2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_WEB_2 }}
          port: ${{ secrets.REMOTE_PORT_WEB_2 }}
          script: |
            echo "Running script..."
            ${{ github.event.client_payload.SCRIPT_RUNNER }}
