name: Deploy CSlant Server - W2

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      SCRIPT_RUNNER:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Deploy to Remote Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_WEB_2 }}
          username: ${{ secrets.REMOTE_USERNAME_WEB_2 }}
          password: ${{ secrets.REMOTE_PASS_WEB_2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_WEB_2 }}
          port: ${{ secrets.REMOTE_PORT_WEB_2 }}
          script: |
            ${{ inputs.SCRIPT_RUNNER }}
